
services:
  postgres:
    build:
      context: .
      dockerfile: src/db/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_recco
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    restart: always
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgres://user:password@postgres:5432/movie_recco
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - ~/.cache/huggingface:/root/.cache/huggingface

  llm:
    build:
      context: .
      dockerfile: src/llm/Dockerfile
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # Match the volume name
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: src/ui/Dockerfile
    restart: always
    volumes:
      - ./src/ui:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

volumes:
  postgres_data:
  ollama_data: 
